CarShop/Areas/Manage/Models/AutoMaker.cs
using Microsoft.AspNetCore.Mvc;
using ShopData.Model;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CarShop.Areas.Manage.Models
{
    public class AutoMaker
    {
        [Display(Name = "Id nhà sản xuất")]
        [Required(ErrorMessage = "{0} Là bắt buộc")]
        public int Id { get; set; }

        [Required(ErrorMessage = "{0} Là bắt buộc")]
        [StringLength(250, ErrorMessage = "{0} Tối đa {1} Ký tự.")]
        [Display(Name = "Tiêu đề")]
        public string Name { get; set; }

        [Display(Name = "Ngày sửa")]
        public string? DateModified { get; set; }

        [StringLength(250, ErrorMessage = "{0} Tối đa {1} Ký tự.")]
        [Display(Name = "Tiêu đề SEO")]
        public string? SeoPageTitle { get; set; }


        [StringLength(250, ErrorMessage = "{0} Tối đa {1} Ký tự.")]
        [Display(Name = "Đường dẫn SEO")]
        //[RegularExpression(@"[^\W+-][+-]*", ErrorMessage = "Chỉ chấp nhận chữ và số và dấu +-")]
        [RegularExpression(@"^[a-z0-9]+(?:-[a-z0-9]+)*$", ErrorMessage = "Chỉ chấp nhận chữ không dấu và số và dấu ' - '")]
        public string? SeoAlias { get; set; }

        [StringLength(250, ErrorMessage = "{0} Tối đa {1} Ký tự.")]
        [Display(Name = "Từ khóa SEO")]
        public string? SeoKeywords { get; set; }

        [StringLength(250, ErrorMessage = "{0} Tối đa {1} Ký tự.")]
        [Display(Name = "Mô tả SEO")]
        public string? SeoDescription { get; set; }

        public bool Status { get; set; }

        public string? AuthorId { get; set; }
        public virtual User Author { get; set; }
        public IFormFile? CoverImage { get; set; }
        public string? Image { set; get; }
    }
}

CarShop/Areas/Manage/Controllers/CarController.cs
using CarShop.Areas.Manage.Models;
using CarShop.Services.GenerateUrlSlug;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.WebUtilities;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using ShopData;
using ShopData.Model;
using System.Text;
using System.Text.RegularExpressions;
using X.PagedList;

namespace CarShop.Areas.Manage.Controllers
{
    public class CarController : ManageController
    {
        private readonly ILogger<AutoMakerController> logger;
        private readonly Context context;
        private readonly UserManager<User> userManage;
        public CarController(ILogger<AutoMakerController> _logger, Context _context, UserManager<User> _userManage)
        {
            logger = _logger;
            context = _context;
            userManage = _userManage;
        }

        public IActionResult Index(int page = 1, int pageSize = 10)
        {
            List<CarModel> model = new List<CarModel>();
            context.Cars
                .Include(e => e.Author)
                .Include(e=>e.CarCategory).ThenInclude(e=>e.Category).OrderByDescending(e=>e.DateCreated)
                .ToList().ForEach(e => {
                var car = new CarModel
                {
                    Id = e.Id,
                    Name = e.Name,
                    Content = e.Content,
                    Price = e.Price,
                    PromoPrice = e.PromoPrice,
                    Author = e.Author,
                    CarCategory = e.CarCategory,
                    CarAutoMaker = e.CarAutoMaker,
                    SeoAlias = e.SeoAlias,
                    Status = e.Status
                };
                if(e.DateModified == null)
                {
                        car.DateModified = e.DateCreated.Value.ToString("dd/MM/yyyy");
                }
                else
                {
                        car.DateModified = e.DateModified.Value.ToString("dd/MM/yyyy");
                }
                string content = Regex.Replace(car.Content, "<[^>]*>", " ");
                car.Content = content.Length > 250 ? content.Substring(0, 250) : content;
                model.Add(car);
            });
            return View(model.ToPagedList(page, pageSize));
        }

        [HttpPost]
        public async Task<IActionResult> SwitchStatus(int? Id)
        {
            if (Id == null)
            {
                return RedirectToAction("Index", "Home");
            }
            var car = context.Cars.Where(e=>e.Id == Id).FirstOrDefault();
            if (car == null)
            {
                return NotFound($"Không tìm thấy Xe với ID '{Id}'.");
            }
            car.Status = !car.Status;
            var res = await context.SaveChangesAsync();
            var SystemMessage = new List<SystemMessage>();
            if (res > 0)
            {
                SystemMessage.Add(new SystemMessage() { Title = "SystemMessageSuccess", Message = "Chuyển trạng thái thành công" });
            }
            else
            {
                SystemMessage.Add(new SystemMessage() { Title = "SystemMessageError", Message = "Chuyển trạng thái thất bại" });
            }
            TempData["SystemMessage"] = JsonConvert.SerializeObject(SystemMessage);
            return RedirectToAction("Index");
        }
        
        [HttpPost]
        public async Task<IActionResult> Delete(int? Id)
        {
            if (Id == null)
            {
                return RedirectToAction("Index", "Home");
            }
            var car = context.Cars.Where(e=>e.Id == Id).FirstOrDefault();
            if (car == null)
            {
                return NotFound($"Không tìm thấy Xe với ID '{Id}'.");
            }
            if (car.CoverImage != null)
            {
                System.IO.File.Delete(Path.Combine(@"wwwroot/", car.CoverImage));
            }
            context.Remove(car);
            var res = await context.SaveChangesAsync();
            var SystemMessage = new List<SystemMessage>();
            if (res > 0)
            {
                SystemMessage.Add(new SystemMessage() { Title = "SystemMessageSuccess", Message = "Xóa thành công" });
            }
            else
            {
                SystemMessage.Add(new SystemMessage() { Title = "SystemMessageError", Message = "Xóa thất bại" });
            }
            TempData["SystemMessage"] = JsonConvert.SerializeObject(SystemMessage);
            return RedirectToAction("Index");
        }

        public IActionResult Create()
        {
            var model = new CarModel();
            model.Categories = context.Categories.ToList();
            model.AutoMakers = context.AutoMakers.ToList();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CarModel model)
        {
            ModelState.Remove("Author");
            ModelState.Remove("CarCategory");
            ModelState.Remove("Categories");
            ModelState.Remove("OldCategoriesId");
            ModelState.Remove("NewCategoriesId");
            ModelState.Remove("CarAutoMaker");
            ModelState.Remove("AutoMakers");
            ModelState.Remove("OldAutoMakersId");
            ModelState.Remove("NewAutoMakersId");
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError(string.Empty, "Lỗi nhập liệu");
                model.Categories = context.Categories.ToList();
                model.AutoMakers = context.AutoMakers.ToList();
                return View(model);
            }
            else
            {
                var car = Activator.CreateInstance<Car>();
                car.Author = await userManage.GetUserAsync(User);
                car.AuthorId = car.Author.Id;
                car.Name = model.Name;
                car.SortDescription = model.SortDescription;
                car.Content = model.Content;
                car.Price = model.Price;
                car.PromoPrice = model.PromoPrice;
                car.Status = model.Status;
                car.Recommended = model.Recommended;
                if (model.SeoPageTitle != null)
                {
                    car.SeoPageTitle = model.SeoPageTitle;
                }
                else
                {
                    car.SeoPageTitle = car.Name;
                }
                if (model.SeoAlias != null)
                {
                    if (car.SeoAlias == model.SeoAlias)
                    {
                        car.SeoAlias = model.SeoAlias;
                    }
                    else
                    {
                        car.SeoAlias = model.SeoAlias;
                        var listAlias = context.Cars.Where(e => e.SeoAlias.Contains(model.SeoAlias) || e.SeoAlias == car.SeoAlias).ToList();
                        if (listAlias.Count > 0)
                        {
                            car.SeoAlias += "-" + listAlias.Count;
                        }
                    }
                }
                else
                {
                    car.SeoAlias = UrlSlug.GenerateSlug(model.Name, false);
                    var listAlias = context.Cars.Where(e => e.SeoAlias.Contains(model.SeoAlias)||e.SeoAlias == car.SeoAlias).ToList();
                    if (listAlias.Count > 0)
                    {
                        car.SeoAlias += "-" + listAlias.Count;
                    }
                }
                if (model.SeoDescription != null)
                {
                    car.SeoDescription = model.SeoDescription;
                }
                else
                {
                    string content = Regex.Replace(model.Content, "<[^>]*>", " ");
                    car.SeoDescription = content.Length > 250 ? content.Substring(0, 250) : content;
                }
                car.SeoKeywords = model.SeoKeywords;
                if (model.CoverImage != null)
                {
                    var folder = string.Format(@"wwwroot/files/coverImage/");
                    if (!Directory.Exists(folder))
                    {
                        Directory.CreateDirectory(folder);
                    }
                    string fileName = Guid.NewGuid() + Path.GetExtension(model.CoverImage.FileName);
                    var filePath = Path.Combine(folder, fileName);

                    using (var stream = System.IO.File.Create(filePath))
                    {
                        await model.CoverImage.CopyToAsync(stream);
                    }
                    car.CoverImage = filePath.Substring(8);
                }
                context.Add(car);
                var res = context.SaveChanges();
                List<SystemMessage> SystemMessage = new List<SystemMessage>();

                if (res > 0)
                {
                    SystemMessage.Add(new SystemMessage() { Title = "SystemMessageSuccess", Message = "Thêm thành công" });
                }
                else
                {
                    SystemMessage.Add(new SystemMessage() { Title = "SystemMessageError", Message = "Thêm thất bại" });
                }

                if(model.NewAutoMakersId != null && model.NewAutoMakersId.Count > 0)
                {
                    List<CarAutoMaker> ListCarAutoMaker = new List<CarAutoMaker>();
                    foreach (var item in model.NewAutoMakersId)
                    {
                        CarAutoMaker carMaker = Activator.CreateInstance<CarAutoMaker>();
                        carMaker.CarId = car.Id;
                        carMaker.AutoMakerId = item;
                        ListCarAutoMaker.Add(carMaker);
                    }
                    await context.AddRangeAsync(ListCarAutoMaker);
                    res = context.SaveChanges();
                    if (res <= 0)
                    {

CarShop/Controllers/AutoMakerController.cs
using CarShop.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ShopData;

namespace CarShop.Controllers
{
    public class AutoMakerController : Controller
    {
        private readonly Context context;
        public AutoMakerController(Context _context)
        {
            context = _context;
        }
        public IActionResult Index(string? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index", "Home");
            }
            var maker = context.AutoMakers.Where(e => e.SeoAlias == id && e.Status == true).FirstOrDefault();
            if (maker == null)
            {
                return NotFound($"Không tìm thấy Xe với ID '{id}'.");
            }
            var categories = context.Categories.Where(e=>e.Status == true).ToList();
            var CarId = context.CarAutoMakers.Where(e => e.AutoMakerId == maker.Id).Select(e => e.CarId).ToList();
            var model = new AutoMakerModel() { 
                AutoMaker = maker, 
                Categories = categories,
                Cars = context.Cars.Where(e=>CarId.Contains(e.Id) && e.Status==true).Include(e=>e.CarCategory).Take(12).ToList() };
            return View(model);
        }
    }
}

CarShop/Views/AutoMaker/Index.cshtml
@model AutoMakerModel
@{
    ViewData["title"] = Model.AutoMaker.Name;
    ViewData["keywords"] = Model.AutoMaker.SeoKeywords;
    ViewData["description"] = Model.AutoMaker.SeoDescription;
}
<!-- Breadcrumb Section Begin -->
<section class="breadcrumb-section set-bg mb-4" data-setbg="/AssetsProducts/img/breadcrumb.jpg">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <div class="breadcrumb__text">
                    <h2>NVH CarShop</h2>
                    <div class="breadcrumb__option">
                        <a href="/">Trang chủ</a>
                        <span>@Model.AutoMaker.Name</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Breadcrumb Section End -->
<!-- Categories Section Begin -->
<section class="categories mt-4">
    <div class="container">
        <div class="row">
            <div class="categories__slider owl-carousel">
                @foreach (var item in Model.Categories)
                {
                    <div class="col-lg-3">
                        <div class="categories__item set-bg" data-setbg="/@(item.CoverImage == null?"img/image-slash.jpg":item.CoverImage)">
                            <h5><a href="/Car?AutoMaker=@Model.AutoMaker.SeoAlias&Category=@item.Id">@item.Name</a></h5>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</section>
<!-- Categories Section End -->
<!-- Featured Section Begin -->
<section class="featured spad mb-4">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="section-title">
                    <h2>Sản phẩm nổi bật</h2>
                </div>
                <div class="featured__controls">
                    <ul>
                        <li class="active" data-filter="*">All</li>
                        @foreach (var item in Model.Categories)
                        {
                            <li data-filter=".@item.Id">@item.Name</li>
                        }
                    </ul>
                </div>
            </div>
        </div>
        <div class="row featured__filter">
            @foreach (var item in Model.Cars)
            {
                <div class="col-lg-3 col-md-4 col-sm-6 mix @String.Join(" ",item.CarCategory.Select(e=>e.CategoryId))">
                    <div class="featured__item">
                        <div class="featured__item__pic set-bg" data-setbg="/@(item.CoverImage == null?"img/image-slash.jpg":item.CoverImage)">
                            <ul class="featured__item__pic__hover">
                                <li><a href="#"><i class="fa fa-heart"></i></a></li>
                                <li><a href="#"><i class="fa fa-retweet"></i></a></li>
                                <li><a href="#"><i class="fa fa-shopping-cart"></i></a></li>
                            </ul>
                        </div>
                        <div class="featured__item__text">
                            <h6><a asp-area="" asp-controller="Car" asp-action="Detail" asp-route-id="@item.SeoAlias">@item.Name</a></h6>
                            @if(item.PromoPrice > 0)
                            {
                                <h6><del>@String.Format("{0:0,0 VND}", item.Price)</del></h6>
                            }
                            <h5 class="text-danger">@String.Format("{0:0,0 VND}", item.Price-item.PromoPrice)</h5>
                        </div>
                    </div>
                </div>
            }
        </div>
        <button onclick="viewMoreFunc()" type="button" style="float:right;color:white;" class="site-btn">Xem thêm</button>
    </div>

</section>

<!-- Featured Section End -->



@*<!-- Banner Begin -->
<div class="banner my-4">
    <div class="container">
        <div class="row">
                <div class="banner__pic">
                    <img src="/AssetsProducts/img/breadcrumb.jpg" alt="">
                </div>
        </div>
    </div>
</div>
<!-- Banner End -->*@

@section Scripts{
    <script>
        function viewMoreFunc(){
            var featured = $(".featured__controls .active"),
            filter = featured.data('filter');
            if(filter =="*"){
                window.location.href = "/Car?AutoMaker=@Model.AutoMaker.SeoAlias";
            }
            else{
                window.location.href = "/Car?AutoMaker=@Model.AutoMaker.SeoAlias&Category="+filter.replace(".","");
            }
            
        }
    </script>
}